fix: CICD use Ruby v3.2
```
sass-embedded-1.77.5-x86_64-linux-gnu requires ruby version >= 3.2
```

See: https://github.com/famiiyu/landing/actions/runs/10244730848/job/28338295476

```
Error: Unknown version 3.3.3 for ruby on ubuntu-22.04
available versions for ruby on ubuntu-22.04: 1.9.3-p551, 2.0.0-p648,
2.1.9, 2.2.10, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7,
2.3.8, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.9,
2.4.10, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8,
2.5.9, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.6.7, 2.6.8,
2.6.9, 2.6.10, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7,
2.7.8, 3.0.0-preview1, 3.0.0-preview2, 3.0.0-rc1, 3.0.0, 3.0.1, 3.0.2,
3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.1.0-preview1, 3.1.0, 3.1.1, 3.1.2,
3.1.3, 3.1.4, 3.2.0-preview1, 3.2.0-preview2, 3.2.0-preview3,
3.2.0-rc1, 3.2.0, 3.2.1, 3.2.2, 3.3.0-preview1, 3.3.0-preview2,
3.3.0-preview3, head, debug
```

See: https://github.com/famiiyu/landing/actions/runs/10244763960/job/28338390673