chore: upgrade ruby v2.7.4 -> v3.3.3
Because installing `jekyll` failed with the following error:

```console
$ gem install bundler jekyll
Fetching bundler-2.5.14.gem
ERROR:  Error installing bundler:
        The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
        bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.4.191.
```